"""
Django settings for ragnarokcp project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import json
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')ko=qpaz+j^9@f&#!&--lkejbf_hq4=y_-o-#i2gm3(m(4sb+a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['alfheim.ro', 'localhost', '127.0.0.1', '151.80.111.103', 'dev.alfheim.ro']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'unitedcp',
    'unitedcp.ragnarok',
    'unitedcp.processors',
    'unitedcp.ragnarok.templatetags',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ragnarokcp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'ragnarokcp/../unitedcp/templates'),
            os.path.join(BASE_DIR, 'ragnarokcp/../unitedcp/addons/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'unitedcp.processors.context_processors.server_name',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'ragnarokcp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ragnarok',
        'USER': 'root',
        'PASSWORD': 'ckflrbqgtc123',
        'HOST': 'localhost',  # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'unitedcp/cache'),
    }
}

LANGUAGES = [
    ('ru', _('Russian')),
    ('en', _('English')),
    ('ar-sa', _('عربي')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ru_ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False

LOGIN_URL = '/auth/register/'
handler404 = 'unitedcp.views.handler404'

# Mail settings
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'noreply@alfheim.ro'
EMAIL_HOST_PASSWORD = 'nNDAUTcmumHxjEVnVuGLoz2y'

VERIFICATION_KEY_EXPIRE = 7

XENFORO_API = 'hPiKXbgCVxx8zCsXQWRyRRiGUUCukxQy'

# If True will also create forum account with master account after email confirm
USE_XENFORO_API = False

# Captcha settings
RECAPTCHA_PUBLIC_KEY = '6LdYWwcUAAAAAGEvF-m_vk5mphbM5U2_TRRKuy28'
RECAPTCHA_PRIVATE_KEY = '6LdYWwcUAAAAAEHXnMnD-F44Q5t0jUb-EIhpffYS'
NOCAPTCHA = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_URL = '/static/'

MEDIA_ROOT = 'unitedcp/static/images/'

# Registration settings
MIN_USERNAME_LENGTH = 4
MAX_USERNAME_LENGTH = 32
MAX_PASSWORD_LENGTH = 32
MIN_PASSWORD_UPPERCASE = 0

CONFIRM_EMAIL = False

# Server settings:
SERVER_NAME = _('Alfheim.RO')
SERVER_URL = 'alfheim.ro'
USE_MD5 = True

SERVER_IP = '151.80.111.103'
LOGIN_PORT = 6900
CHAR_PORT = 6121
MAP_PORT = 5121

SERVER_STATUS_UPDATE = 360 * 60  # in seconds
SERVER_ONLINE_UPDATE = 30  # in seconds

# Donations settings:
DONATION_RATE = float(1.0)  # Donations rate

YANDEX_MONEY_ENABLED = True
YANDEX_MONEY_WALLET = 410015549656067
YANDEX_MONEY_KEY = 'x/HIeLeDQxBoHXqHUA/6e9Sn'

# Download links
"""
    Add your download links below in format:
    {
        'name': 'Name of file hosting / cloud service',
        'link': 'Download link',
        'size': 'File size e.g. 100MB',
        'image': 'Image path e.g. images/download/name.png',
        'description': 'Some description of file',
        'date': 'Upload date',
        'short_desc': 'Short description like "Light Patcher or Full Client"'
    },
"""
DOWNLOAD = [
    {
        'name': 'Direct link',
        'link': 'http://mega.com',
        'size': '2.5ГБ',
        'image': '',
        'description': '100% working!',
        'date': '20.02.2017',
        'short_desc': 'Full client'
    }
]

# Groupd IDs
ADMIN = 99
GAME_MASTER = 70
EVENTER = 50
HELPER = 20
SUPER_PLAYER = 1
NORMAL_PLAYER = 0

# Map settings
# Default map for 'Reset character' function
DEFAULT_MAP = 'prontera'
DEFAULT_X = 150
DEFAULT_Y = 150

# Ratings:
MIN_BASE_LEVEL = 99

SERVER_SETTINGS = {

    # Exp settings
    'BaseExpRate': 1000,
    'JobExpRate': 1000,
    'QuestExpRate': 1000,
    'MvPExpRate': 100,

    # Drop settings:
    'Common': 1000,
    'CommonBoss': 500,
    'Heal': 1000,
    'HealBoss': 500,
    'Useable': 1000,
    'UseableBoss': 500,
    'Equip': 1000,
    'EquipBoss': 500,
    'Card': 500,
    'CardBoss': 100,
    'MvpItem': 100
}

SOCIAL_LINKS = {
    # vk.com
    'VK': 'https://vk.com/alfheimro',
    # facebook.com
    'FB': '',
    # twitter.com
    'TW': '',
    # instagram.com
    'IN': '',
    # youtube.com
    'YT': '',
    # discordapp.com
    'DS': 'https://discord.gg/nzMREJV',
    # your forum url
    'Forum': 'https://community.alfheim.ro/',
}

SOCIAL_WIDGETS = {
    # vk.com
    'VK': '...',
    # facebook.com
    'FB': '...',
    # twitter.com
    'TW': '...',
    # discordapp.com
    'DS': '...',
}

RANDOM_TITLES = [
    _('Наши EDP бьют сильнее (на самом деле нет)'),
    _('Это как будто сказать всем, что ты болен, а самому пойти на пляж, - только для РОшников.'),
    _('Как в 2007, только в 2017'),
    _('При игре становится только лучше!'),
    _('Наши Ханты распивают один авак на троих!'),
    _('Играть саппортами - солидно!'),
    _('У нас Кафры следят за Вами по GPS')
]

# # Staff json
# with open(os.path.join(BASE_DIR, 'unitedcp/fixtures/staff.json')) as a:
#     DEVELOPERS = json.load(a)
#
# # Email template
# with open(os.path.join(BASE_DIR, 'unitedcp/fixtures/confirm_email_template.html')) as a:
#     HTML_TEMPLATE = a.read().replace('\n', '')
#
# # Verification template
# with open(os.path.join(BASE_DIR, 'unitedcp/fixtures/user_verification_template.html')) as a:
#     VERIFY_TEMPLATE = a.read().replace('\n', '')

GUIDE_MAX_IMAGE_SIZE = 300000  # 300KB
VALID_EXTENTIONS = [
    '.png',
    '.jpg',
    '.bmp'
]
