# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import unitedcp.accounts.models
import unitedcp.guides.models
import unitedcp.shop.models
import unitedcp.staff.news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldQuests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wq_title', models.CharField(max_length=100)),
                ('wq_category', models.SmallIntegerField()),
                ('wq_description', models.TextField(blank=True, null=True)),
                ('wq_location', models.CharField(max_length=100)),
                ('wq_type', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'world_quests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WqCategories',
            fields=[
                ('category_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'wq_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WqPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.IntegerField()),
                ('char_id', models.IntegerField()),
            ],
            options={
                'db_table': 'wq_player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WqRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('zeny', models.IntegerField()),
                ('quest_id', models.IntegerField()),
            ],
            options={
                'db_table': 'wq_rewards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CPNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Title')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('description', models.TextField(default='', max_length=10000, verbose_name='Description')),
                ('main_image', models.ImageField(default='', upload_to=unitedcp.staff.news.models.upload_news, verbose_name='Main Image')),
                ('news_type', models.CharField(choices=[('Patch Note', 'Patch Note'), ('Event', 'Event'), ('News', 'News')], default='Patch Note', max_length=20, verbose_name='Type')),
                ('author', models.CharField(default='', max_length=150, verbose_name='Author')),
                ('link', models.URLField(default='', verbose_name='Source url')),
                ('publish', models.BooleanField(default=False, verbose_name='Publish')),
            ],
            options={
                'db_table': 'cp_news',
            },
        ),
        migrations.CreateModel(
            name='CPNewsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to=unitedcp.staff.news.models.upload_images, verbose_name='Images')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitedcp.CPNews')),
            ],
            options={
                'db_table': 'cp_news_images',
            },
        ),
        migrations.CreateModel(
            name='CPNewsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=150, verbose_name='Tags')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unitedcp.CPNews')),
            ],
            options={
                'db_table': 'cp_news_tags',
            },
        ),
        migrations.CreateModel(
            name='DonationsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default='', max_length=1000, verbose_name='Payment ID')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('log', models.CharField(default='', max_length=1000, verbose_name='Log')),
                ('error_code', models.IntegerField(default=0, verbose_name='Error Code')),
                ('payment_system', models.CharField(default='', max_length=1000, verbose_name='Payment System')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('donate_value', models.FloatField(default=0, verbose_name='Donation Value')),
                ('points_value', models.FloatField(default=0, verbose_name='Points Value')),
                ('user', models.IntegerField(default=0, verbose_name='AccountID')),
            ],
            options={
                'verbose_name': 'Donations',
                'db_table': 'cp_donatelog',
            },
        ),
        migrations.CreateModel(
            name='MasterAccountStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PanelLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, default=0, null=True)),
                ('action', models.CharField(default='', max_length=500)),
                ('code', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(default='')),
                ('agent', models.CharField(default='', max_length=1000)),
                ('device', models.CharField(default='', max_length=1000)),
                ('os', models.CharField(default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Panel Logs',
                'db_table': 'cp_panel_log',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=150, verbose_name='Item Name')),
                ('item_cost', models.FloatField(default=0, verbose_name='Cost')),
                ('item_discount', models.FloatField(default=0, help_text='Discount in percents', verbose_name='Discount')),
                ('item_discount_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Discount date starts')),
                ('item_discount_until', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Discount date ends')),
                ('item_id', models.IntegerField(default=0, verbose_name='Item ID')),
                ('item_amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('item_extra', models.IntegerField(default=0, verbose_name='Extra services')),
                ('item_image_thumbnail', models.FileField(default='', max_length=500, upload_to=unitedcp.shop.models.upload_thumbnail, verbose_name='Thumbnail image')),
                ('item_sale_ends', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Discount sale date end')),
            ],
            options={
                'verbose_name': 'Shop',
                'db_table': 'cp_shop',
            },
        ),
        migrations.CreateModel(
            name='ShopBundles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(default='', max_length=150, verbose_name='Bundle Name')),
                ('item_id', models.IntegerField(default=0, verbose_name='Item ID')),
                ('item_amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('item_extra', models.IntegerField(default=0, verbose_name='Extra services')),
            ],
            options={
                'verbose_name': 'Shop Bundles',
                'db_table': 'cp_shop_bundles',
            },
        ),
        migrations.CreateModel(
            name='ShopCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=150, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Item Shop Categories',
                'db_table': 'cp_shop_categories',
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, default=0, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('announce_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Sell', 'Sell'), ('Exchange', 'Exchange'), ('Other', 'Other')], default=1, max_length=20, verbose_name='Type')),
                ('main_character', models.CharField(blank=True, default='Char', max_length=36, null=True)),
                ('message', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('announce_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created date')),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Updated date')),
            ],
            options={
                'db_table': 'cp_user_announcements',
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncementsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, default=0, null=True)),
                ('character', models.CharField(blank=True, default='Char', max_length=36, null=True)),
                ('message', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('comment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date')),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unitedcp.UserAnnouncements')),
            ],
            options={
                'db_table': 'cp_user_comments',
            },
        ),
        migrations.CreateModel(
            name='UserGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('category', models.CharField(choices=[('quest_guide', 'Quest Guide'), ('class_guide', 'Class Guide'), ('other', 'Other')], default='', max_length=30)),
                ('on_moderation', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('main_image', models.ImageField(default='', upload_to=unitedcp.guides.models.guide_upload, validators=[unitedcp.guides.models.main_image_validation], verbose_name='Main Image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cp_user_guides',
            },
        ),
        migrations.CreateModel(
            name='UserGuideReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('quest_guide', 'Quest Guide'), ('class_guide', 'Class Guide'), ('other', 'Other')], default='', max_length=30)),
                ('reward_id', models.IntegerField(default=0)),
                ('reward_amount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'cp_user_guide_rewards',
            },
        ),
        migrations.CreateModel(
            name='UserGuideTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=100)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unitedcp.UserGuide')),
            ],
            options={
                'db_table': 'cp_user_guide_tags',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_points', models.IntegerField(default=0, verbose_name='Donation Points')),
                ('ro_character', models.IntegerField(default=0, verbose_name='Character ID')),
                ('viewable', models.BooleanField(default=False, verbose_name='Viewable Profile')),
                ('user_avatar', models.FileField(max_length=500, upload_to=unitedcp.accounts.models.upload_avatar, verbose_name='Avatar')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='Phone')),
                ('receive_notifications', models.BooleanField(default=False, verbose_name='Receive Notifications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cp_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_id', models.IntegerField(default=0)),
                ('reward_amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rewards',
                'db_table': 'cp_user_rewards',
            },
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=255, unique=True, verbose_name='Verification Key')),
                ('verification_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('key_expires', models.DateTimeField()),
                ('action', models.IntegerField(default=0, verbose_name='Action')),
                ('new_value', models.CharField(default='', max_length=255, verbose_name='Value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User verification',
                'db_table': 'cp_user_verification',
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='item_bundle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unitedcp.ShopBundles', verbose_name='Is bundle'),
        ),
        migrations.AddField(
            model_name='shop',
            name='item_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='unitedcp.ShopCategories', verbose_name='Category'),
        ),
    ]
