# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unitedcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='item_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unitedcp.ShopBundles', verbose_name='Is bundle'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='unitedcp.ShopCategories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='item_discount_from',
            field=models.DateTimeField(null=True, verbose_name='Discount date starts'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='item_discount_until',
            field=models.DateTimeField(null=True, verbose_name='Discount date ends'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='item_extra',
            field=models.IntegerField(choices=[(0, 'Nothing'), (1, 'Name change'), (2, 'Account transfer')], default=0, verbose_name='Extra services'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='item_sale_ends',
            field=models.DateTimeField(null=True, verbose_name='Sale date end'),
        ),
    ]
