# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(default='', max_length=1000, verbose_name='Payment ID')),
                ('finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('log', models.CharField(default='', max_length=1000, verbose_name='Log')),
                ('error_code', models.IntegerField(default=0, verbose_name='Error Code')),
                ('payment_system', models.CharField(default='', max_length=1000, verbose_name='Payment System')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('donate_value', models.FloatField(default=0, verbose_name='Donation Value')),
                ('points_value', models.FloatField(default=0, verbose_name='Points Value')),
                ('user', models.IntegerField(default=0, verbose_name='AccountID')),
            ],
            options={
                'verbose_name': 'Donations',
                'db_table': 'cp_donatelog',
            },
        ),
    ]
